version: "3.8"
services:
  mysqlocal:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - sabanaRed
  api:
    image: danieludea28/api-recurzo-confi
      #Cuando quiera construir la imagen desde cero
    #build:
     # context: ./
      #dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysqlocal
    depends_on:
      - mysqlocal
    networks:
      - sabanaRed
networks:
  sabanaRed:
