name: Build image Docker

on:
  push:
    branches: [ "miFakeDevelop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: danieludea28/grandeJose
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.MI_USUARIO_DE_DOCKER }}
          password: ${{ secrets.MI_SUPER_CLAVE }}
